name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        config-path: ${{ inputs.config-path }}
    - name: cheking the branch
      run: |
        git branch
        git remote -v
        
